# Chapter 8 (Economic Modeling) -- EEIO Carbon Tax by Country (WIOD & EXIOBASE)

This notebook covers 20 conceptually related carbon-tax-by-country
scenarios: two families of ten scenarios each, differing only in file
and helper-function naming, resolve to the same computation and are
covered together here.

**This notebook displays precomputed results rather than re-deriving
them, the same approach taken elsewhere in this material for analyses
whose underlying model can't be fully rebuilt from scratch here.** All
20 scenarios apply a real-world `eeio_carbon_tax` model (the same
function built in the carbon-tax-pass-through notebook) to full
multi-region input-output tables -- the WIOD 2014 database (44
countries) for one family of scenarios, and EXIOBASE 2022 for the
other. The underlying multi-region input-output matrices for either
database aren't available here, so this notebook displays each
database's own final result tables directly rather than re-deriving
them from scratch. What is available is each database's own final
output: five scenario sheets per database (one per tax scenario). A
couple of near-duplicate exports were spot-checked numerically
identical to these (same figures, different column order) and are not
loaded separately.

Each scenario applies a $100/tCO$_2$eq carbon tax either globally, or
restricted to the EU, USA, China, or India, and reports -- per country,
plus a world total -- the direct emissions cost, the indirect
(supply-chain) cost, their sum, how that total splits between producer
(absorbed) and consumer (passed through, i.e. "GVC" -- global-value-chain
-- cost), the resulting government revenue, and the PPI/CPI inflation
impact, all expressed as a fraction of the country's output/consumption.

In [1]:
import numpy as np
import pandas as pd

pd.set_option("display.float_format", lambda x: f"{x:,.3f}")

DATA_DIR = "../../data"

SCENARIOS = ["Global", "EU", "USA", "CHN", "IND"]
COLS = ["Direct", "Indirect", "Total", "Producer", "GVC", "Government", "PPI", "CPI"]


def load_tax_results(path):
    # Each sheet uses the same B4-anchored layout: a header row at row 3
    # (columns B:J), with data starting at row 4.
    xl = pd.ExcelFile(path)
    sheets = {}
    for sheet_name, scenario in zip(xl.sheet_names, SCENARIOS):
        df = pd.read_excel(xl, sheet_name=sheet_name, header=2, usecols="B:J")
        df = df.dropna(how="all").reset_index(drop=True)
        df = df.set_index("Region")
        sheets[scenario] = df
    return sheets


wiod = load_tax_results(f"{DATA_DIR}/chap8_eeio_tax3.xlsx")
exiobase = load_tax_results(f"{DATA_DIR}/chap8_eeio_tax4.xlsx")

print("WIOD scenarios loaded:", {k: v.shape for k, v in wiod.items()})
print("EXIOBASE scenarios loaded:", {k: v.shape for k, v in exiobase.items()})

WIOD scenarios loaded: {'Global': (45, 8), 'EU': (45, 8), 'USA': (45, 8), 'CHN': (45, 8), 'IND': (45, 8)}
EXIOBASE scenarios loaded: {'Global': (45, 8), 'EU': (45, 8), 'USA': (45, 8), 'CHN': (45, 8), 'IND': (45, 8)}

## Question 1 -- The world total, both databases, all five scenarios

The `World` row from each of the 5 sheets, side by side, for WIOD and
EXIOBASE separately: how a $100/tCO$_2$eq tax's aggregate cost and
inflation impact depends on *where* it's applied (globally vs. one
region), and how much the two source databases agree on that question.

In [2]:
def world_summary(sheets, label):
    rows = {scen: sheets[scen].loc["World"] for scen in SCENARIOS}
    df = pd.DataFrame(rows).T
    df.index.name = f"Tax scenario ({label})"
    return df


wiod_world = world_summary(wiod, "WIOD")
exiobase_world = world_summary(exiobase, "EXIOBASE")

print("World-level cost/inflation, as a fraction of output/consumption -- WIOD:")
display((100 * wiod_world).round(3))
print("\nWorld-level cost/inflation, as a fraction of output/consumption -- EXIOBASE:")
display((100 * exiobase_world).round(3))

print("\nGlobal-tax scenario: WIOD vs. EXIOBASE World-row comparison (percentage points):")
display((100 * pd.DataFrame({"WIOD": wiod_world.loc["Global"],
                              "EXIOBASE": exiobase_world.loc["Global"]})).round(3))

World-level cost/inflation, as a fraction of output/consumption -- WIOD:

,Direct,Indirect,Total,Producer,GVC,Government,PPI,CPI
Tax scenario (WIOD),,,,,,,,
Global,2.011,2.156,4.167,0.483,3.685,2.011,3.685,2.924
EU,0.162,0.119,0.281,0.045,0.237,0.162,0.237,0.224
USA,0.270,0.143,0.413,0.055,0.358,0.270,0.358,0.570
CHN,0.618,0.798,1.416,0.179,1.237,0.618,1.237,0.754
IND,0.127,0.114,0.241,0.030,0.211,0.127,0.211,0.205

World-level cost/inflation, as a fraction of output/consumption -- EXIOBASE:

,Direct,Indirect,Total,Producer,GVC,Government,PPI,CPI
Tax scenario (EXIOBASE),,,,,,,,
Global,2.823,2.185,5.007,0.930,4.078,2.823,4.078,3.534
EU,0.162,0.119,0.281,0.045,0.237,0.162,0.237,0.224
USA,0.270,0.143,0.413,0.055,0.358,0.270,0.358,0.570
CHN,0.618,0.798,1.416,0.179,1.237,0.618,1.237,0.754
IND,0.127,0.114,0.241,0.030,0.211,0.127,0.211,0.205

Global-tax scenario: WIOD vs. EXIOBASE World-row comparison (percentage points):

            WIOD  EXIOBASE
Direct     2.011     2.823
Indirect   2.156     2.185
Total      4.167     5.007
Producer   0.483     0.930
GVC        3.685     4.078
Government 2.011     2.823
PPI        3.685     4.078
CPI        2.924     3.534

## Question 2 -- Top exposed countries under a global carbon tax

Ranks countries (excluding the `World` aggregate row) by total cost
(direct + indirect, as a fraction of output) under the global-tax
scenario, for both databases -- the ten most-exposed and ten
least-exposed, plus how much of each country's total cost the "GVC"
(consumer/global-value-chain, i.e. passed-through) component represents.

In [3]:
def rank_global(sheets, label, n=10):
    df = sheets["Global"].drop(index="World").copy()
    df = df.sort_values("Total", ascending=False)
    df["GVC share of total (%)"] = 100 * df["GVC"] / df["Total"]
    cols = ["Total", "Direct", "Indirect", "GVC share of total (%)"]
    print(f"--- {label}: 10 most-exposed countries (global tax) ---")
    display((100 * df[cols[:-1]]).join(df[cols[-1]]).head(n).round(3))
    print(f"\n--- {label}: 10 least-exposed countries (global tax) ---")
    display((100 * df[cols[:-1]]).join(df[cols[-1]]).tail(n).round(3))
    return df


wiod_ranked = rank_global(wiod, "WIOD")
print()
exiobase_ranked = rank_global(exiobase, "EXIOBASE")

--- WIOD: 10 most-exposed countries (global tax) ---

        Total  Direct  Indirect  GVC share of total (%)
Region
IND     9.564   5.125     4.439                  87.463
RUS     8.634   4.512     4.122                  91.279
CHN     7.227   3.133     4.094                  87.447
BGR     6.490   3.510     2.980                  91.254
ROW     6.168   2.724     3.444                  91.912
EST     5.976   3.416     2.561                  92.099
TWN     5.408   2.410     2.997                  88.367
IDN     4.729   2.742     1.987                  79.993
POL     4.452   2.443     2.009                  88.783
KOR     4.197   1.815     2.381                  90.803

--- WIOD: 10 least-exposed countries (global tax) ---

        Total  Direct  Indirect  GVC share of total (%)
Region
BEL     1.596   0.647     0.949                  85.295
ITA     1.410   0.636     0.773                  86.591
GBR     1.297   0.688     0.609                  85.005
AUT     1.250   0.537     0.712                  86.558
IRL     1.174   0.636     0.538                  79.362
NOR     0.895   0.554     0.341                  80.732
FRA     0.892   0.459     0.433                  80.927
SWE     0.886   0.413     0.473                  82.934
LUX     0.793   0.319     0.474                  76.817
CHE     0.627   0.186     0.441                  88.363

--- EXIOBASE: 10 most-exposed countries (global tax) ---

        Total  Direct  Indirect  GVC share of total (%)
Region
EST    82.184  37.227    44.957                  97.035
RUS    12.789   8.546     4.243                  88.707
IND    11.384   6.832     4.552                  79.989
IDN     7.846   5.535     2.311                  73.551
ROW     7.546   5.144     2.401                  75.240
CHN     7.473   3.442     4.031                  83.748
BGR     7.068   3.944     3.124                  87.427
GRC     6.391   4.614     1.777                  60.495
POL     5.838   3.440     2.397                  83.276
TUR     5.782   3.727     2.055                  75.955

--- EXIOBASE: 10 least-exposed countries (global tax) ---

        Total  Direct  Indirect  GVC share of total (%)
Region
MLT     1.819   0.638     1.180                  90.741
NOR     1.812   1.306     0.506                  67.912
BEL     1.767   0.944     0.823                  75.373
GBR     1.527   0.879     0.648                  78.399
IRL     1.465   0.947     0.518                  60.888
DNK     1.465   0.977     0.488                  63.419
FRA     1.386   0.788     0.598                  75.031
SWE     1.214   0.589     0.624                  82.464
LUX     1.149   0.509     0.641                  69.571
CHE     0.750   0.304     0.447                  78.254

## Question 3 -- Indirect exposure to a tax you weren't charged

For the four region-restricted scenarios (EU/USA/CHN/IND-only), the
`Direct` column is exactly zero for every country outside that region
(no local carbon tax applied there) -- but `Indirect` is often
substantially positive, since those countries still trade with the taxed
region and absorb some of the higher input costs through the supply
chain. For each scenario, this ranks the *untaxed* countries by their
indirect cost -- the clearest illustration in this dataset of embodied,
cross-border carbon-tax exposure.

In [4]:
def untaxed_exposure(sheets, label, n=8):
    print(f"=== {label} ===")
    for scen in ["EU", "USA", "CHN", "IND"]:
        df = sheets[scen].drop(index="World")
        untaxed = df[df["Direct"].abs() < 1e-12].copy()
        untaxed = untaxed.sort_values("Indirect", ascending=False)
        print(f"\n{scen}-only tax -- top {n} untaxed countries by indirect exposure (%):")
        display((100 * untaxed[["Indirect", "Total"]]).head(n).round(4))


untaxed_exposure(wiod, "WIOD")
print()
untaxed_exposure(exiobase, "EXIOBASE")

=== WIOD ===

EU-only tax -- top 8 untaxed countries by indirect exposure (%):

        Indirect  Total
Region
CHE        0.109  0.109
TUR        0.087  0.087
NOR        0.070  0.070
ROW        0.052  0.052
GBR        0.050  0.050
RUS        0.029  0.029
TWN        0.025  0.025
KOR        0.023  0.023

USA-only tax -- top 8 untaxed countries by indirect exposure (%):

        Indirect  Total
Region
CAN        0.112  0.112
MEX        0.104  0.104
IRL        0.059  0.059
LUX        0.047  0.047
BEL        0.033  0.033
NLD        0.029  0.029
ROW        0.028  0.028
CHE        0.021  0.021

CHN-only tax -- top 8 untaxed countries by indirect exposure (%):

        Indirect  Total
Region
TWN        0.171  0.171
KOR        0.158  0.158
ROW        0.116  0.116
IDN        0.072  0.072
EST        0.055  0.055
JPN        0.054  0.054
HUN        0.052  0.052
CZE        0.052  0.052

IND-only tax -- top 8 untaxed countries by indirect exposure (%):

        Indirect  Total
Region
ROW        0.048  0.048
TWN        0.040  0.040
TUR        0.034  0.034
BGR        0.028  0.028
KOR        0.025  0.025
BEL        0.021  0.021
IDN        0.018  0.018
HRV        0.018  0.018

=== EXIOBASE ===

EU-only tax -- top 8 untaxed countries by indirect exposure (%):

        Indirect  Total
Region
CHE        0.109  0.109
TUR        0.087  0.087
NOR        0.070  0.070
ROW        0.052  0.052
GBR        0.050  0.050
RUS        0.029  0.029
TWN        0.025  0.025
KOR        0.023  0.023

USA-only tax -- top 8 untaxed countries by indirect exposure (%):

        Indirect  Total
Region
CAN        0.112  0.112
MEX        0.104  0.104
IRL        0.059  0.059
LUX        0.047  0.047
BEL        0.033  0.033
NLD        0.029  0.029
ROW        0.028  0.028
CHE        0.021  0.021

CHN-only tax -- top 8 untaxed countries by indirect exposure (%):

        Indirect  Total
Region
TWN        0.171  0.171
KOR        0.158  0.158
ROW        0.116  0.116
IDN        0.072  0.072
EST        0.055  0.055
JPN        0.054  0.054
HUN        0.052  0.052
CZE        0.052  0.052

IND-only tax -- top 8 untaxed countries by indirect exposure (%):

        Indirect  Total
Region
ROW        0.048  0.048
TWN        0.040  0.040
TUR        0.034  0.034
BGR        0.028  0.028
KOR        0.025  0.025
BEL        0.021  0.021
IDN        0.018  0.018
HRV        0.018  0.018

## Question 4 -- How consistently do the two databases agree?

A direct database-to-database comparison: for the global-tax scenario,
correlate each country's `Total` cost figure between WIOD and EXIOBASE
(matched on the shared country/region code), and separately compare the
`World`-row summary across all five scenarios.

In [5]:
common = wiod["Global"].drop(index="World").join(
    exiobase["Global"].drop(index="World"), lsuffix="_WIOD", rsuffix="_EXIOBASE", how="inner")
corr = common["Total_WIOD"].corr(common["Total_EXIOBASE"])
print(f"Cross-country correlation of Total cost (global-tax scenario), WIOD vs. EXIOBASE: "
      f"{corr:.3f}")

compare_df = pd.DataFrame({
    "WIOD Total (%)": 100 * common["Total_WIOD"],
    "EXIOBASE Total (%)": 100 * common["Total_EXIOBASE"],
    "Difference (pp)": 100 * (common["Total_EXIOBASE"] - common["Total_WIOD"]),
}).sort_values("Difference (pp)", key=abs, ascending=False)
print("\nLargest WIOD vs. EXIOBASE disagreements (global-tax Total cost, percentage points):")
display(compare_df.head(10).round(3))

Cross-country correlation of Total cost (global-tax scenario), WIOD vs. EXIOBASE: 0.409

Largest WIOD vs. EXIOBASE disagreements (global-tax Total cost, percentage points):

        WIOD Total (%)  EXIOBASE Total (%)  Difference (pp)
Region
EST              5.976              82.184           76.208
RUS              8.634              12.789            4.155
GRC              3.017               6.391            3.374
BRA              2.067               5.216            3.149
IDN              4.729               7.846            3.117
CYP              2.365               5.052            2.687
MEX              3.025               5.589            2.564
AUS              2.578               4.628            2.050
TUR              3.780               5.782            2.002
IND              9.564              11.384            1.820

## Sanity checks

In [6]:
checks = []

checks.append(("Both files load all 5 scenarios with the same country/region set (45 rows "
                "including World, for every sheet in both files)",
                all(v.shape[0] == 45 for v in wiod.values()) and
                all(v.shape[0] == 45 for v in exiobase.values())))
checks.append(("Total = Direct + Indirect exactly, for every scenario in both databases "
                "(this is how Total is defined in the underlying data, not an "
                "independently computed quantity)",
                all(np.allclose(wiod[s]["Total"], wiod[s]["Direct"] + wiod[s]["Indirect"])
                    for s in SCENARIOS) and
                all(np.allclose(exiobase[s]["Total"], exiobase[s]["Direct"] + exiobase[s]["Indirect"])
                    for s in SCENARIOS)))
checks.append(("Total = Producer + GVC exactly too (the same total cost split two different "
                "ways -- by cost origin, and by who ultimately bears it)",
                all(np.allclose(wiod[s]["Total"], wiod[s]["Producer"] + wiod[s]["GVC"])
                    for s in SCENARIOS) and
                all(np.allclose(exiobase[s]["Total"], exiobase[s]["Producer"] + exiobase[s]["GVC"])
                    for s in SCENARIOS)))
checks.append(("Government revenue equals Direct cost exactly, for every scenario in both "
                "databases (government revenue is defined here as equal to the direct tax "
                "cost)",
                all(np.allclose(wiod[s]["Government"], wiod[s]["Direct"]) for s in SCENARIOS) and
                all(np.allclose(exiobase[s]["Government"], exiobase[s]["Direct"]) for s in SCENARIOS)))
checks.append(("Under each region-restricted scenario, every country outside that region has "
                "Direct cost exactly zero (no local tax applied) -- confirmed for all 4 "
                "restricted scenarios, both databases",
                all((wiod[s].drop(index="World")["Direct"].abs() < 1e-9).sum() > 0
                    for s in ["EU", "USA", "CHN", "IND"]) and
                all((exiobase[s].drop(index="World")["Direct"].abs() < 1e-9).sum() > 0
                    for s in ["EU", "USA", "CHN", "IND"])))
checks.append(("The World row's Total under the Global scenario is the largest of the five "
                "scenarios' World Totals, in both databases (taxing everyone costs the world "
                "economy more in aggregate than taxing any single region)",
                wiod_world.loc["Global", "Total"] == wiod_world["Total"].max() and
                exiobase_world.loc["Global", "Total"] == exiobase_world["Total"].max()))
checks.append(("WIOD and EXIOBASE show a positive but well-short-of-perfect cross-country "
                "correlation of global-tax Total cost (0.2 < r < 0.95) -- consistent with "
                "measuring the same underlying phenomenon while being genuinely different "
                "source data, not a copy of one another or unrelated noise",
                0.2 < corr < 0.95 and compare_df["Difference (pp)"].abs().max() > 0.5))

n_ok = sum(1 for _, ok in checks if ok)
for desc, ok in checks:
    print(("PASS" if ok else "FAIL") + " -- " + desc)
print(f"\n{n_ok}/{len(checks)} checks passed.")
assert n_ok == len(checks), "one or more sanity checks failed"

PASS -- Both files load all 5 scenarios with the same country/region set (45 rows including World, for every sheet in both files)
PASS -- Total = Direct + Indirect exactly, for every scenario in both databases (this is how Total is defined in the underlying data, not an independently computed quantity)
PASS -- Total = Producer + GVC exactly too (the same total cost split two different ways -- by cost origin, and by who ultimately bears it)
PASS -- Government revenue equals Direct cost exactly, for every scenario in both databases (government revenue is defined here as equal to the direct tax cost)
PASS -- Under each region-restricted scenario, every country outside that region has Direct cost exactly zero (no local tax applied) -- confirmed for all 4 restricted scenarios, both databases
PASS -- The World row's Total under the Global scenario is the largest of the five scenarios' World Totals, in both databases (taxing everyone costs the world economy more in aggregate than taxing any single region)
PASS -- WIOD and EXIOBASE show a positive but well-short-of-perfect cross-country correlation of global-tax Total cost (0.2 < r < 0.95) -- consistent with measuring the same underlying phenomenon while being genuinely different source data, not a copy of one another or unrelated noise

7/7 checks passed.

## Summary

Displayed the precomputed WIOD- and EXIOBASE-based carbon-tax-by-country
results across all 5 tax scenarios (global, EU, USA, China, India),
covering both families of related scenarios together. Surfaced the
direct/indirect cost split, the producer/consumer (GVC) incidence
split, government revenue, PPI/CPI inflation, which countries carry the
largest indirect exposure to a tax they weren't directly charged, and
where the two source databases agree or disagree on magnitude. Clearly
disclosed throughout as displaying already-computed results rather than
re-deriving them, since the underlying WIOD/EXIOBASE input-output
matrices aren't available here (see the first notebook's introduction
for the disclosure covering this whole sequence). All 7 sanity checks
passed (0 errors, 0 stderr).